[tool.poetry]
name = "gpt-logger"
version = "0.1.0"
description = ""
authors = ["Jij :)"]

[tool.poetry.dependencies]
gunicorn = "^21.2.0"
python = "^3.10"
flask = "^2.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
